export const TUWI_27_CURRICULUM_MAP = [
  {
    lessonId: 1,
    topicEnglish: "Alphabet and Nouns",
    topicVietnamese: "Bảng chữ cái và Danh từ",
    slug: "alphabet-and-nouns",
    sourceLessons: [],
    status: "partial",
    notes: "Chưa có nội dung tương ứng trong bộ Gateway cũ.",
  },
  {
    lessonId: 2,
    topicEnglish: "TOPIC 2 — SINGULAR & PLURAL NOUNS",
    topicVietnamese: "Danh từ số ít & Danh từ số nhiều",
    slug: "singular-plural-nouns",
    sourceLessons: [],
    status: "ready",
    notes: "Nội dung Buổi 2 đã được biên soạn đầy đủ; video đang dùng placeholder an toàn.",
  },
  {
    lessonId: 3,
    topicEnglish: "(Un)Countable Nouns",
    topicVietnamese: "Danh từ đếm được & không đếm được",
    slug: "countable-uncountable-nouns",
    sourceLessons: [13],
    status: "reused",
    notes: "Tái sử dụng buổi cũ về đồ ăn thức uống và danh từ đếm được/không đếm được.",
  },
  {
    lessonId: 4,
    topicEnglish: "Personal pronoun",
    topicVietnamese: "Đại từ nhân xưng",
    slug: "personal-pronoun",
    sourceLessons: [],
    status: "ready",
    notes: "Đã tích hợp đầy đủ nội dung Personal Pronouns theo kiến trúc Buổi 9.",
  },
  {
    lessonId: 5,
    topicEnglish: "To be Verb",
    topicVietnamese: "Động từ to be",
    slug: "to-be-verb",
    sourceLessons: [2, 3],
    status: "merged",
    notes: "Gộp các phần to be khẳng định/phủ định/câu hỏi từ Unit 1.",
  },
  {
    lessonId: 6,
    topicEnglish: "This That These Those",
    topicVietnamese: "Đại từ chỉ định",
    slug: "this-that-these-those",
    sourceLessons: [6],
    status: "reused",
    notes: "Tái sử dụng buổi cũ về đồ vật hằng ngày và demonstratives.",
  },
  {
    lessonId: 7,
    topicEnglish: "There is - There are",
    topicVietnamese: "Cấu trúc There is/There are",
    slug: "there-is-there-are",
    sourceLessons: [11],
    status: "reused",
    notes: "Tái sử dụng buổi cũ về các phòng và There is/are.",
  },
  {
    lessonId: 8,
    topicEnglish: "Capital letter rules",
    topicVietnamese: "Nguyên tắc viết hoa",
    slug: "capital-letter-rules",
    sourceLessons: [],
    status: "draft",
    notes: "Chưa có nội dung cũ phù hợp.",
  },
  {
    lessonId: 9,
    topicEnglish: "Possessives",
    topicVietnamese: "Sở hữu",
    slug: "possessives",
    sourceLessons: [4],
    status: "reused",
    notes: "Tái sử dụng phần possessive adjectives/have got.",
  },
  {
    lessonId: 10,
    topicEnglish: "Preposition of Place",
    topicVietnamese: "Giới từ vị trí",
    slug: "preposition-of-place",
    sourceLessons: [12],
    status: "reused",
    notes: "Tái sử dụng buổi cũ về đồ nội thất và giới từ vị trí.",
  },
  {
    lessonId: 11,
    topicEnglish: "Preposition of Time",
    topicVietnamese: "Giới từ thời gian",
    slug: "preposition-of-time",
    sourceLessons: [],
    status: "draft",
    notes: "Chưa có buổi cũ tách riêng giới từ thời gian.",
  },
  {
    lessonId: 12,
    topicEnglish: "Prepositions of Movement",
    topicVietnamese: "Giới từ chỉ sự chuyển động",
    slug: "prepositions-of-movement",
    sourceLessons: [31],
    status: "reused",
    notes: "Buổi 31 cũ có phần ôn giới từ A1, dùng tạm làm nguồn tham chiếu.",
  },
  {
    lessonId: 13,
    topicEnglish: "Modal verbs",
    topicVietnamese: "Động từ khuyết thiếu",
    slug: "modal-verbs",
    sourceLessons: [14, 29],
    status: "merged",
    notes: "Gộp các phần can/can't, must/should và be going to từ bộ cũ.",
  },
  {
    lessonId: 14,
    topicEnglish: "Conjunctions",
    topicVietnamese: "Liên từ",
    slug: "conjunctions",
    sourceLessons: [31],
    status: "reused",
    notes: "Tái sử dụng phần linking words trong buổi 31 cũ.",
  },
  {
    lessonId: 15,
    topicEnglish: "Present Simple Tense",
    topicVietnamese: "Hiện tại đơn",
    slug: "present-simple-tense",
    sourceLessons: [8, 9],
    status: "merged",
    notes: "Gộp hiện tại đơn khẳng định/phủ định/câu hỏi.",
  },
  {
    lessonId: 16,
    topicEnglish: "Present Continuous Tense",
    topicVietnamese: "Hiện tại tiếp diễn",
    slug: "present-continuous-tense",
    sourceLessons: [17, 18],
    status: "merged",
    notes: "Gộp hiện tại tiếp diễn và câu hỏi hiện tại tiếp diễn.",
  },
  {
    lessonId: 17,
    topicEnglish: "Present Simple & Present Continuous",
    topicVietnamese: "Hiện tại đơn & tiếp diễn",
    slug: "present-simple-and-continuous",
    sourceLessons: [19],
    status: "reused",
    notes: "Tái sử dụng buổi so sánh hai thì.",
  },
  {
    lessonId: 18,
    topicEnglish: "Quantifiers: some, any, many, much",
    topicVietnamese: "Lượng từ",
    slug: "quantifiers",
    sourceLessons: [13],
    status: "reused",
    notes: "Buổi danh từ đếm được/không đếm được có phần lượng từ liên quan.",
  },
  {
    lessonId: 19,
    topicEnglish: "Adjectives/Adverbs",
    topicVietnamese: "Tính từ/Trạng từ",
    slug: "adjectives-adverbs",
    sourceLessons: [16],
    status: "reused",
    notes: "Tái sử dụng buổi trạng từ chỉ cách thức.",
  },
  {
    lessonId: 20,
    topicEnglish: "Comparisons",
    topicVietnamese: "So sánh hơn, so sánh nhất",
    slug: "comparisons",
    sourceLessons: [26, 27],
    status: "merged",
    notes: "Gộp so sánh hơn và so sánh nhất từ Unit 9 cũ.",
  },
  {
    lessonId: 21,
    topicEnglish: "WH Questions",
    topicVietnamese: "Từ để hỏi",
    slug: "wh-questions",
    sourceLessons: [31],
    status: "reused",
    notes: "Tái sử dụng phần Wh-questions trong buổi 31 cũ.",
  },
  {
    lessonId: 22,
    topicEnglish: "Simple future - Near future",
    topicVietnamese: "Tương lai đơn - Tương lai gần",
    slug: "simple-future-near-future",
    sourceLessons: [29],
    status: "reused",
    notes: "Tái sử dụng phần be going to từ buổi du lịch.",
  },
  {
    lessonId: 23,
    topicEnglish: "Numbers and Time in English",
    topicVietnamese: "Số đếm, số thứ tự, ngày, tháng & giờ",
    slug: "numbers-and-time-in-english",
    sourceLessons: [],
    status: "ready",
    notes: "Nội dung Buổi 23 đã được biên soạn đầy đủ theo flow Buổi 9.",
  },
  {
    lessonId: 24,
    topicEnglish: "Past Simple",
    topicVietnamese: "Quá khứ đơn",
    slug: "past-simple",
    sourceLessons: [20, 21, 22, 23, 24, 25],
    status: "merged",
    notes: "Gộp các phần quá khứ đơn to be, động từ có quy tắc/bất quy tắc, phủ định và câu hỏi.",
  },
  {
    lessonId: 25,
    topicEnglish: "Past Continuous Tense",
    topicVietnamese: "Quá khứ tiếp diễn",
    slug: "past-continuous-tense",
    sourceLessons: [],
    status: "ready",
    notes: "Đã tích hợp đầy đủ nội dung Past Continuous theo kiến trúc Buổi 9; video dùng placeholder an toàn.",
  },
  {
    lessonId: 26,
    topicEnglish: "Tag Questions",
    topicVietnamese: "Câu hỏi đuôi",
    slug: "tag-questions",
    sourceLessons: [],
    status: "ready",
    notes: "Đã tích hợp đầy đủ nội dung Tag Questions theo kiến trúc Buổi 9.",
  },
  {
    lessonId: 27,
    topicEnglish: "Perfect present Tense",
    topicVietnamese: "Thì hiện tại hoàn thành",
    slug: "perfect-present-tense",
    sourceLessons: [28],
    status: "reused",
    notes: "Tái sử dụng buổi địa lý và hiện tại hoàn thành.",
  },
];
