export const IPA_BOOTCAMP_SECTION_FLOW = [
  "ipa_intro",
  "ipa_why",
  "ipa_word_process",
  "ipa_sound_table",
  "ipa_mouth_visual",
  "ipa_video_mouth",
  "ipa_mouth_opening",
  "ipa_audio_samples",
  "ipa_read_symbols",
  "ipa_compare_sounds",
  "ipa_spell_words",
  "ipa_image_sentence",
  "ipa_blend_words",
  "ipa_listen_choose_sound",
  "ipa_self_reading",
  "ipa_sentence_practice",
  "ipa_ai_speaking",
  "ipa_mini_test",
  "ipa_mindmap",
  "ipa_homework",
];

const VIDEO_SLOTS = [
  "VIDEO_SLOT_INTRO_IPA_PROCESS",
  "VIDEO_SLOT_SOUND_I_SHORT",
  "VIDEO_SLOT_SOUND_E",
  "VIDEO_SLOT_SOUND_AE",
  "VIDEO_SLOT_SOUND_CARET",
  "VIDEO_SLOT_SOUND_O_SHORT",
  "VIDEO_SLOT_SOUND_U_SHORT",
];

const LESSON_1_SOUNDS = [
  {
    symbol: "/ɪ/",
    name: "i ngắn",
    word: "sit",
    ipa: "/sɪt/",
    sentence: "I sit.",
    mouth: {
      lips: "môi hơi mở, kéo nhẹ sang hai bên",
      tongue: "lưỡi cao vừa, hơi đưa ra trước",
      teeth: "răng mở hẹp",
      air: "hơi tự nhiên, ngắn",
      voice: "có rung",
      mistake: "đọc quá dài thành /iː/",
    },
  },
  {
    symbol: "/e/",
    name: "e ngắn",
    word: "pen",
    ipa: "/pen/",
    sentence: "This is a pen.",
    mouth: {
      lips: "môi mở vừa, hơi dẹt",
      tongue: "lưỡi ở giữa, đầu lưỡi gần răng dưới",
      teeth: "răng mở vừa",
      air: "hơi tự nhiên",
      voice: "có rung",
      mistake: "đọc thành /æ/ quá mở",
    },
  },
  {
    symbol: "/æ/",
    name: "a bẹt",
    word: "cat",
    ipa: "/kæt/",
    sentence: "This is a cat.",
    mouth: {
      lips: "môi mở rộng",
      tongue: "lưỡi thấp, hơi đưa ra trước",
      teeth: "răng mở rõ",
      air: "hơi tự nhiên",
      voice: "có rung",
      mistake: "đọc thành /e/",
    },
  },
  {
    symbol: "/ʌ/",
    name: "ơ ngắn",
    word: "cup",
    ipa: "/kʌp/",
    sentence: "This is a cup.",
    mouth: {
      lips: "môi thả lỏng",
      tongue: "lưỡi thấp vừa, ở giữa miệng",
      teeth: "răng mở vừa",
      air: "hơi ngắn và nhẹ",
      voice: "có rung",
      mistake: "đọc thành âm /a/ tiếng Việt",
    },
  },
  {
    symbol: "/ɒ/",
    name: "o ngắn",
    word: "dog",
    ipa: "/dɒg/",
    sentence: "This is a dog.",
    mouth: {
      lips: "môi tròn nhẹ",
      tongue: "lưỡi thấp, lùi về sau",
      teeth: "răng mở",
      air: "hơi tự nhiên",
      voice: "có rung",
      mistake: "đọc quá giống /ɔː/",
    },
  },
  {
    symbol: "/ʊ/",
    name: "u ngắn",
    word: "book",
    ipa: "/bʊk/",
    sentence: "This is a book.",
    mouth: {
      lips: "môi tròn nhẹ, không chu quá mạnh",
      tongue: "lưỡi cao vừa, lùi về sau",
      teeth: "răng mở hẹp",
      air: "hơi ngắn",
      voice: "có rung",
      mistake: "đọc thành /uː/ quá dài",
    },
  },
];

const LESSON_1_IMAGES = [
  { word: "sit", ipa: "/sɪt/", sentence: "I sit.", slot: "IMAGE_SLOT_SIT" },
  { word: "pen", ipa: "/pen/", sentence: "This is a pen.", slot: "IMAGE_SLOT_PEN" },
  { word: "cat", ipa: "/kæt/", sentence: "This is a cat.", slot: "IMAGE_SLOT_CAT" },
  { word: "cup", ipa: "/kʌp/", sentence: "This is a cup.", slot: "IMAGE_SLOT_CUP" },
  { word: "dog", ipa: "/dɒg/", sentence: "This is a dog.", slot: "IMAGE_SLOT_DOG" },
  { word: "book", ipa: "/bʊk/", sentence: "This is a book.", slot: "IMAGE_SLOT_BOOK" },
];

const LESSON_1_BLEND_GAME = [
  { sounds: ["/k/", "/æ/", "/t/"], answer: "cat" },
  { sounds: ["/p/", "/e/", "/n/"], answer: "pen" },
  { sounds: ["/k/", "/ʌ/", "/p/"], answer: "cup" },
  { sounds: ["/b/", "/ʊ/", "/k/"], answer: "book" },
];

const LESSON_1_LISTEN_GAME = [
  { audioText: "cat", answer: "/æ/", options: ["/æ/", "/e/", "/ʌ/", "/ʊ/"] },
  { audioText: "pen", answer: "/e/", options: ["/ɪ/", "/e/", "/æ/", "/ɒ/"] },
  { audioText: "cup", answer: "/ʌ/", options: ["/ʌ/", "/ɒ/", "/e/", "/ʊ/"] },
  { audioText: "book", answer: "/ʊ/", options: ["/uː/", "/ɪ/", "/ʊ/", "/ɒ/"] },
];

export const IPA_BOOTCAMP_CURRICULUM_MAP = [
  {
    lessonId: 1,
    topicEnglish: "IPA Foundation – Cách đọc một từ tiếng Anh",
    topicVietnamese: "Nền tảng phát âm cho người mất gốc",
    slug: "ipa-foundation-cach-doc-mot-tu-tieng-anh",
    sourceLessons: [],
    status: "ready",
    notes: "Buổi 1 IPA Foundation thay thế Buổi 1 Alphabet and Nouns cũ.",
  },
  {
    lessonId: 2,
    topicEnglish: "Short vs Long Vowels – Nguyên âm ngắn và dài",
    topicVietnamese: "Phân biệt âm ngắn và âm dài",
    slug: "short-vs-long-vowels",
    sourceLessons: [],
    status: "ready",
    notes: "IPA Bootcamp lesson.",
  },
  {
    lessonId: 3,
    topicEnglish: "Diphthongs – Nguyên âm đôi",
    topicVietnamese: "Học cách đọc âm trượt",
    slug: "diphthongs-nguyen-am-doi",
    sourceLessons: [],
    status: "ready",
    notes: "IPA Bootcamp lesson.",
  },
  {
    lessonId: 4,
    topicEnglish: "Stop Sounds & Nasals – Âm bật và âm mũi",
    topicVietnamese: "Bật âm rõ, không nuốt âm cuối",
    slug: "stop-sounds-and-nasals",
    sourceLessons: [],
    status: "ready",
    notes: "IPA Bootcamp lesson.",
  },
  {
    lessonId: 5,
    topicEnglish: "Fricatives – Âm gió / âm ma sát",
    topicVietnamese: "Phân biệt hơi và rung giọng",
    slug: "fricatives-am-gio-am-ma-sat",
    sourceLessons: [],
    status: "ready",
    notes: "IPA Bootcamp lesson.",
  },
  {
    lessonId: 6,
    topicEnglish: "Difficult Consonants – Âm dễ sai với người Việt",
    topicVietnamese: "Sửa lỗi ch, j, l, r, w, y",
    slug: "difficult-consonants",
    sourceLessons: [],
    status: "ready",
    notes: "IPA Bootcamp lesson.",
  },
  {
    lessonId: 7,
    topicEnglish: "Word Stress & Schwa – Trọng âm và âm /ə/",
    topicVietnamese: "Biết vì sao tiếng Anh không đọc đều từng chữ",
    slug: "word-stress-and-schwa",
    sourceLessons: [],
    status: "ready",
    notes: "IPA Bootcamp lesson.",
  },
  {
    lessonId: 8,
    topicEnglish: "IPA Review – Tổng ôn IPA và đọc từ/câu",
    topicVietnamese: "Tổng ôn 44 âm + đọc từ + đọc câu",
    slug: "ipa-review-tong-on",
    sourceLessons: [],
    status: "ready",
    notes: "IPA Bootcamp review lesson.",
  },
];

export const IPA_BOOTCAMP_LESSONS = [
  createIpaLesson({
    id: 1,
    title: "IPA Foundation – Cách đọc một từ tiếng Anh",
    subtitle: "Nền tảng phát âm cho người mất gốc",
    topic: "Tổng quan IPA + nguyên âm ngắn",
    learningItems: "/ɪ/ /e/ /æ/ /ʌ/ /ɒ/ /ʊ/",
    outcome: "Học sinh hiểu IPA là gì, biết đọc 6 nguyên âm ngắn cơ bản, biết nhìn khẩu hình miệng/lưỡi/răng/môi để bắt chước âm.",
    sectionFlow: IPA_BOOTCAMP_SECTION_FLOW,
    sounds: LESSON_1_SOUNDS,
    videoSlots: VIDEO_SLOTS,
    imageSlots: LESSON_1_IMAGES,
    blendGame: LESSON_1_BLEND_GAME,
    listenChooseGame: LESSON_1_LISTEN_GAME,
    minitest: [
      { q: "IPA giúp em làm gì?", options: ["Nhìn ký hiệu để biết cách đọc", "Dịch văn bản dài", "Học toán", "Viết hoa tên riêng"], answer: 0 },
      { q: "Dấu /ː/ nghĩa là gì?", options: ["kéo dài âm", "đọc nhỏ lại", "bỏ âm cuối", "đọc thật nhanh"], answer: 0 },
      { q: "Từ cat có âm chính nào hôm nay?", options: ["/æ/", "/ʊ/", "/ɒ/", "/ɪ/"], answer: 0 },
      { q: "Từ book có âm chính nào hôm nay?", options: ["/ʊ/", "/e/", "/æ/", "/ʌ/"], answer: 0 },
      { q: "Khi học phát âm cần quan sát gì?", options: ["môi, lưỡi, răng, hơi", "màu bút", "số trang", "chữ viết hoa"], answer: 0 },
    ],
  }),
  createIpaLesson({
    id: 2,
    title: "Short vs Long Vowels – Nguyên âm ngắn và dài",
    subtitle: "Phân biệt âm ngắn và âm dài",
    topic: "Nguyên âm dài",
    learningItems: "/iː/ /uː/ /ɑː/ /ɔː/ /ɜː/",
    outcome: "Học sinh hiểu dấu /ː/ là kéo dài âm, phân biệt được âm ngắn và âm dài.",
  }),
  createIpaLesson({
    id: 3,
    title: "Diphthongs – Nguyên âm đôi",
    subtitle: "Học cách đọc âm trượt",
    topic: "Nguyên âm đôi",
    learningItems: "/eɪ/ /aɪ/ /ɔɪ/ /aʊ/ /əʊ/ /ɪə/ /eə/ /ʊə/",
    outcome: "Học sinh biết đọc các âm trượt như say, time, boy, house, go.",
  }),
  createIpaLesson({
    id: 4,
    title: "Stop Sounds & Nasals – Âm bật và âm mũi",
    subtitle: "Bật âm rõ, không nuốt âm cuối",
    topic: "Phụ âm bật + âm mũi",
    learningItems: "/p/ /b/ /t/ /d/ /k/ /g/ /m/ /n/ /ŋ/",
    outcome: "Học sinh biết bật âm cuối, đọc rõ các âm p/b/t/d/k/g và âm mũi m/n/ng.",
  }),
  createIpaLesson({
    id: 5,
    title: "Fricatives – Âm gió / âm ma sát",
    subtitle: "Phân biệt hơi và rung giọng",
    topic: "Phụ âm gió / ma sát",
    learningItems: "/f/ /v/ /θ/ /ð/ /s/ /z/ /ʃ/ /ʒ/ /h/",
    outcome: "Học sinh phân biệt s/z, f/v, th hữu thanh/vô thanh, sh và zh.",
  }),
  createIpaLesson({
    id: 6,
    title: "Difficult Consonants – Âm dễ sai với người Việt",
    subtitle: "Sửa lỗi ch, j, l, r, w, y",
    topic: "Âm ch, j, l, r, w, y",
    learningItems: "/tʃ/ /dʒ/ /l/ /r/ /w/ /j/",
    outcome: "Học sinh sửa các lỗi Việt Nam hay gặp như l/r, w/v, ch/j.",
  }),
  createIpaLesson({
    id: 7,
    title: "Word Stress & Schwa – Trọng âm và âm /ə/",
    subtitle: "Biết vì sao tiếng Anh không đọc đều từng chữ",
    topic: "Trọng âm + âm schwa",
    learningItems: "word stress, syllable, /ə/",
    outcome: "Học sinh hiểu trọng âm, âm tiết, âm schwa; biết vì sao teacher, banana, about không đọc đều từng chữ.",
  }),
  createIpaLesson({
    id: 8,
    title: "IPA Review – Tổng ôn IPA và đọc từ/câu",
    subtitle: "Tổng ôn 44 âm + đọc từ + đọc câu",
    topic: "Tổng ôn IPA + đọc từ/câu",
    learningItems: "44 âm + đọc 50 từ + 20 câu",
    outcome: "Học sinh có thể nhìn IPA, nghe audio, tự luyện đọc từ mới và đọc câu ngắn.",
  }),
];

function createIpaLesson({
  id,
  title,
  subtitle,
  topic,
  learningItems,
  outcome,
  sectionFlow = ["ipa_intro", "ipa_sound_table", "ipa_audio_samples", "ipa_self_reading", "ipa_mini_test", "ipa_homework"],
  sounds = createSoundList(learningItems),
  videoSlots = ["VIDEO_SLOT_IPA_PLACEHOLDER"],
  imageSlots = [],
  blendGame = [],
  listenChooseGame = [],
  minitest = createDefaultIpaMinitest(topic),
}){
  return {
    id,
    unit: "IPA Bootcamp",
    title,
    titleEn: title,
    titleVi: subtitle,
    subtitle,
    cefrLevel: "A1",
    mainTopic: topic,
    topicEnglish: title,
    topicVietnamese: subtitle,
    slug: IPA_BOOTCAMP_CURRICULUM_MAP.find((entry) => entry.lessonId === id)?.slug,
    status: {
      content: "ready",
      code: "ipa",
      import: "manual",
    },
    curriculumStatus: "ready",
    module: "ipa-bootcamp",
    sectionFlow,
    objectives: [
      `Chủ đề: ${topic}.`,
      `Học gì: ${learningItems}.`,
      outcome,
    ],
    ipa: {
      topic,
      learningItems,
      outcome,
      sounds,
      videoSlots,
      imageSlots,
      blendGame,
      listenChooseGame,
    },
    vocabulary: sounds.map((sound) => ({
      en: sound.word || sound.symbol,
      vi: sound.name || topic,
      ipa: sound.ipa || sound.symbol,
      example: sound.sentence || "",
      group: "ipaSounds",
    })),
    vocabGroups: {
      ipaSounds: "IPA sounds",
      practiceWords: "Practice words",
    },
    minitest,
    homework: [
      `Đọc lại các âm: ${learningItems}.`,
      "Ghi âm 5 từ mẫu và gửi giáo viên sửa phát âm.",
    ],
    metadata: {
      contentImported: true,
      localContentAuthoritative: true,
      sourceLessonIds: [],
      status: {
        content: "ready",
        code: "ipa",
        import: "manual",
      },
    },
  };
}

function createSoundList(learningItems){
  return String(learningItems)
    .split(/\s+/)
    .filter(Boolean)
    .map((symbol) => ({
      symbol,
      name: "âm IPA",
      word: symbol.replace(/\//g, ""),
      ipa: symbol,
      sentence: `Listen and repeat ${symbol}.`,
      mouth: {
        lips: "quan sát môi theo video mẫu",
        tongue: "đặt lưỡi theo hướng dẫn của giáo viên",
        teeth: "giữ răng mở tự nhiên",
        air: "đẩy hơi đều",
        voice: "kiểm tra rung giọng khi cần",
        mistake: "đọc theo thói quen tiếng Việt",
      },
    }));
}

function createDefaultIpaMinitest(topic){
  return [
    { q: `Bài hôm nay tập trung vào nội dung nào?`, options: [topic, "Past simple", "Possessives", "Capital letters"], answer: 0 },
    { q: "Khi luyện phát âm, bước nào quan trọng nhất?", options: ["Nghe - nhìn khẩu hình - nhắc lại", "Chép 20 lần", "Dịch sang tiếng Việt", "Bỏ âm cuối"], answer: 0 },
    { q: "Nếu chưa có audio thật, em nên dùng gì trong app?", options: ["nút nghe placeholder/TTS", "bỏ qua bài", "đổi bài", "tắt trình duyệt"], answer: 0 },
  ];
}
