create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  phone text,
  email text,
  role text not null default 'student',
  status text not null default 'pending',
  note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.profiles
  add column if not exists full_name text,
  add column if not exists phone text,
  add column if not exists email text,
  add column if not exists role text not null default 'student',
  add column if not exists status text not null default 'pending',
  add column if not exists note text,
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists updated_at timestamptz not null default now();

alter table public.profiles
  alter column full_name drop not null,
  alter column role set default 'student',
  alter column status set default 'pending';

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'profiles_role_check'
      and conrelid = 'public.profiles'::regclass
  ) then
    alter table public.profiles
      add constraint profiles_role_check check (role in ('admin', 'student'));
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'profiles_status_check'
      and conrelid = 'public.profiles'::regclass
  ) then
    alter table public.profiles
      add constraint profiles_status_check check (status in ('pending', 'approved', 'rejected', 'blocked'));
  end if;
end $$;

create table if not exists public.lessons (
  id bigint generated by default as identity primary key,
  lesson_number int not null unique,
  slug text not null unique,
  title text not null,
  topic_english text not null,
  topic_vietnamese text not null,
  description text,
  status text not null default 'draft',
  content jsonb not null default '{}'::jsonb,
  source_lessons jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint lessons_status_check check (status in ('ready', 'partial', 'draft', 'empty', 'reused', 'merged'))
);

create table if not exists public.student_lesson_progress (
  id uuid default gen_random_uuid() primary key,
  student_id uuid not null references auth.users(id) on delete cascade,
  lesson_id bigint not null references public.lessons(id) on delete cascade,
  status text not null default 'not_started',
  progress_percent int not null default 0,
  completed_at timestamptz,
  last_opened_at timestamptz,
  data jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(student_id, lesson_id),
  constraint student_lesson_progress_status_check check (status in ('not_started', 'in_progress', 'completed')),
  constraint student_lesson_progress_percent_check check (progress_percent between 0 and 100)
);

create table if not exists public.student_activity_logs (
  id uuid default gen_random_uuid() primary key,
  student_id uuid references auth.users(id) on delete cascade,
  lesson_id bigint references public.lessons(id) on delete set null,
  action text not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.admin_student_notes (
  id uuid default gen_random_uuid() primary key,
  student_id uuid not null references auth.users(id) on delete cascade,
  admin_id uuid references auth.users(id) on delete set null,
  note text not null,
  created_at timestamptz not null default now()
);

create or replace function public.update_updated_at_column()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists update_profiles_updated_at on public.profiles;
create trigger update_profiles_updated_at
before update on public.profiles
for each row execute function public.update_updated_at_column();

drop trigger if exists update_lessons_updated_at on public.lessons;
create trigger update_lessons_updated_at
before update on public.lessons
for each row execute function public.update_updated_at_column();

drop trigger if exists update_student_lesson_progress_updated_at on public.student_lesson_progress;
create trigger update_student_lesson_progress_updated_at
before update on public.student_lesson_progress
for each row execute function public.update_updated_at_column();

create or replace function public.is_admin(user_id uuid)
returns boolean
language sql
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.profiles
    where id = user_id
      and role = 'admin'
      and status = 'approved'
  );
$$;

create or replace function public.is_approved_student(user_id uuid)
returns boolean
language sql
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.profiles
    where id = user_id
      and role in ('student', 'admin')
      and status = 'approved'
  );
$$;

alter table public.profiles enable row level security;
alter table public.lessons enable row level security;
alter table public.student_lesson_progress enable row level security;
alter table public.student_activity_logs enable row level security;
alter table public.admin_student_notes enable row level security;

drop policy if exists "Users can view own profile" on public.profiles;
create policy "Users can view own profile"
on public.profiles for select
to authenticated
using (auth.uid() = id);

drop policy if exists "Users can update own basic profile" on public.profiles;
create policy "Users can update own basic profile"
on public.profiles for update
to authenticated
using (auth.uid() = id)
with check (
  auth.uid() = id
  and role = (select role from public.profiles where id = auth.uid())
  and status = (select status from public.profiles where id = auth.uid())
);

drop policy if exists "Admins can view all profiles" on public.profiles;
create policy "Admins can view all profiles"
on public.profiles for select
to authenticated
using (public.is_admin(auth.uid()));

drop policy if exists "Admins can update profile moderation fields" on public.profiles;
create policy "Admins can update profile moderation fields"
on public.profiles for update
to authenticated
using (public.is_admin(auth.uid()))
with check (public.is_admin(auth.uid()));

drop policy if exists "Public can read lesson rows" on public.lessons;
drop policy if exists "Approved students can read lesson rows" on public.lessons;
drop policy if exists "Admins can read lesson rows" on public.lessons;
create policy "Admins can read lesson rows"
on public.lessons for select
to authenticated
using (public.is_admin(auth.uid()));

drop policy if exists "Admins can write lessons" on public.lessons;
create policy "Admins can write lessons"
on public.lessons for all
to authenticated
using (public.is_admin(auth.uid()))
with check (public.is_admin(auth.uid()));

drop policy if exists "Students can read own progress" on public.student_lesson_progress;
create policy "Students can read own progress"
on public.student_lesson_progress for select
to authenticated
using (student_id = auth.uid());

drop policy if exists "Students can insert own progress" on public.student_lesson_progress;
create policy "Students can insert own progress"
on public.student_lesson_progress for insert
to authenticated
with check (student_id = auth.uid());

drop policy if exists "Students can update own progress" on public.student_lesson_progress;
create policy "Students can update own progress"
on public.student_lesson_progress for update
to authenticated
using (student_id = auth.uid())
with check (student_id = auth.uid());

drop policy if exists "Admins can read all progress" on public.student_lesson_progress;
create policy "Admins can read all progress"
on public.student_lesson_progress for select
to authenticated
using (public.is_admin(auth.uid()));

drop policy if exists "Students can insert own activity" on public.student_activity_logs;
create policy "Students can insert own activity"
on public.student_activity_logs for insert
to authenticated
with check (student_id = auth.uid());

drop policy if exists "Students can read own activity" on public.student_activity_logs;
create policy "Students can read own activity"
on public.student_activity_logs for select
to authenticated
using (student_id = auth.uid());

drop policy if exists "Admins can read all activity" on public.student_activity_logs;
create policy "Admins can read all activity"
on public.student_activity_logs for select
to authenticated
using (public.is_admin(auth.uid()));

drop policy if exists "Admins can manage student notes" on public.admin_student_notes;
create policy "Admins can manage student notes"
on public.admin_student_notes for all
to authenticated
using (public.is_admin(auth.uid()))
with check (public.is_admin(auth.uid()));

create index if not exists lessons_lesson_number_idx on public.lessons(lesson_number);
create index if not exists student_lesson_progress_student_idx on public.student_lesson_progress(student_id);
create index if not exists student_lesson_progress_lesson_idx on public.student_lesson_progress(lesson_id);
create index if not exists student_activity_logs_student_idx on public.student_activity_logs(student_id);
create index if not exists student_activity_logs_lesson_idx on public.student_activity_logs(lesson_id);
create index if not exists admin_student_notes_student_idx on public.admin_student_notes(student_id);

do $$
declare
  table_name text;
begin
  foreach table_name in array array[
    'profiles',
    'lessons',
    'student_lesson_progress',
    'student_activity_logs'
  ]
  loop
    if not exists (
      select 1
      from pg_publication_tables
      where pubname = 'supabase_realtime'
        and schemaname = 'public'
        and tablename = table_name
    ) then
      execute format('alter publication supabase_realtime add table public.%I', table_name);
    end if;
  end loop;
end $$;
