-- Setup extensions
create extension if not exists pgcrypto;

-- 1. Profiles Table
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  full_name text,
  phone text,
  role text not null default 'student',
  status text not null default 'pending',
  note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.profiles drop constraint if exists profiles_role_check;
alter table public.profiles add constraint profiles_role_check check (role in ('admin', 'student'));

alter table public.profiles drop constraint if exists profiles_status_check;
alter table public.profiles add constraint profiles_status_check check (status in ('pending', 'approved', 'rejected'));

alter table public.profiles drop constraint if exists profiles_email_key;
alter table public.profiles add constraint profiles_email_key unique (email);

-- 2. Classes Table
create table if not exists public.classes (
  id uuid default gen_random_uuid() primary key,
  name text not null,
  description text,
  level text default 'A1',
  status text not null default 'active',
  created_by uuid references auth.users(id) on delete set null default auth.uid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.classes drop constraint if exists classes_status_check;
alter table public.classes add constraint classes_status_check check (status in ('active', 'archived'));

-- 3. Class Memberships Table
create table if not exists public.class_memberships (
  id uuid default gen_random_uuid() primary key,
  class_id uuid not null references public.classes(id) on delete cascade,
  student_id uuid not null references auth.users(id) on delete cascade,
  status text not null default 'pending',
  approved_by uuid references auth.users(id) on delete set null,
  approved_at timestamptz,
  rejected_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(class_id, student_id)
);

alter table public.class_memberships drop constraint if exists class_memberships_status_check;
alter table public.class_memberships add constraint class_memberships_status_check check (status in ('pending', 'approved', 'rejected', 'removed'));

-- 4. Lessons Table
create table if not exists public.lessons (
  id bigint generated by default as identity primary key,
  lesson_number int not null unique,
  slug text not null unique,
  title text not null,
  topic_english text not null,
  topic_vietnamese text not null,
  description text,
  status text not null default 'draft',
  content jsonb not null default '{}'::jsonb,
  source_lessons jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.lessons drop constraint if exists lessons_status_check;
alter table public.lessons add constraint lessons_status_check check (status in ('ready', 'partial', 'draft', 'empty', 'reused', 'merged'));

-- 5. Student Lesson Progress Table
create table if not exists public.student_lesson_progress (
  id uuid default gen_random_uuid() primary key,
  student_id uuid not null references auth.users(id) on delete cascade,
  class_id uuid references public.classes(id) on delete set null,
  lesson_id bigint not null references public.lessons(id) on delete cascade,
  status text not null default 'not_started',
  progress_percent int not null default 0,
  completed_at timestamptz,
  last_opened_at timestamptz,
  data jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(student_id, lesson_id)
);

alter table public.student_lesson_progress drop constraint if exists student_lesson_progress_status_check;
alter table public.student_lesson_progress add constraint student_lesson_progress_status_check check (status in ('not_started', 'in_progress', 'completed'));

alter table public.student_lesson_progress drop constraint if exists student_lesson_progress_percent_check;
alter table public.student_lesson_progress add constraint student_lesson_progress_percent_check check (progress_percent between 0 and 100);

-- 6. Student Activity Logs Table
create table if not exists public.student_activity_logs (
  id uuid default gen_random_uuid() primary key,
  student_id uuid references auth.users(id) on delete cascade,
  lesson_id bigint references public.lessons(id) on delete set null,
  action text not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

-- Enable RLS for all tables
alter table public.profiles enable row level security;
alter table public.classes enable row level security;
alter table public.class_memberships enable row level security;
alter table public.lessons enable row level security;
alter table public.student_lesson_progress enable row level security;
alter table public.student_activity_logs enable row level security;

-- 7. Security Definer helper functions to avoid recursion in RLS policies
create or replace function public.is_admin(user_id uuid)
returns boolean
language sql
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.profiles
    where id = user_id
      and role = 'admin'
      and status = 'approved'
  );
$$;

create or replace function public.is_approved_student(user_id uuid)
returns boolean
language sql
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.profiles
    where id = user_id
      and role = 'student'
      and status = 'approved'
  );
$$;

create or replace function public.is_class_member(user_id uuid, target_class_id uuid)
returns boolean
language sql
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.class_memberships
    where student_id = user_id
      and class_id = target_class_id
      and status = 'approved'
  );
$$;

create or replace function public.profile_role_status_unchanged(profile_id uuid, new_role text, new_status text)
returns boolean
language sql
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.profiles
    where id = profile_id
      and role = new_role
      and status = new_status
  );
$$;

-- 8. Clean up and recreate RLS policies
-- profiles policies
drop policy if exists "Profiles are readable by owner" on public.profiles;
drop policy if exists "Profiles are readable by admins" on public.profiles;
drop policy if exists "Users can update own contact fields only" on public.profiles;
drop policy if exists "Admins can update profiles" on public.profiles;

create policy "Profiles are readable by owner"
on public.profiles for select
to authenticated
using (auth.uid() = id);

create policy "Profiles are readable by admins"
on public.profiles for select
to authenticated
using (public.is_admin(auth.uid()));

create policy "Users can update own contact fields only"
on public.profiles for update
to authenticated
using (auth.uid() = id)
with check (
  auth.uid() = id
  and public.profile_role_status_unchanged(id, role, status)
);

create policy "Admins can update profiles"
on public.profiles for update
to authenticated
using (public.is_admin(auth.uid()))
with check (public.is_admin(auth.uid()));

-- classes policies
drop policy if exists "Admins can manage classes" on public.classes;
drop policy if exists "Approved students can read active classes" on public.classes;

create policy "Admins can manage classes"
on public.classes for all
to authenticated
using (public.is_admin(auth.uid()))
with check (public.is_admin(auth.uid()));

create policy "Approved students can read active classes"
on public.classes for select
to authenticated
using (status = 'active' and (public.is_approved_student(auth.uid()) or public.is_admin(auth.uid())));

-- class_memberships policies
drop policy if exists "Students can read own class memberships" on public.class_memberships;
drop policy if exists "Students can request class membership" on public.class_memberships;
drop policy if exists "Admins can read class memberships" on public.class_memberships;
drop policy if exists "Admins can update class memberships" on public.class_memberships;

create policy "Students can read own class memberships"
on public.class_memberships for select
to authenticated
using (student_id = auth.uid());

create policy "Students can request class membership"
on public.class_memberships for insert
to authenticated
with check (
  student_id = auth.uid()
  and status = 'pending'
  and approved_by is null
  and approved_at is null
  and rejected_at is null
  and public.is_approved_student(auth.uid())
);

create policy "Admins can read class memberships"
on public.class_memberships for select
to authenticated
using (public.is_admin(auth.uid()));

create policy "Admins can update class memberships"
on public.class_memberships for update
to authenticated
using (public.is_admin(auth.uid()))
with check (public.is_admin(auth.uid()));

-- lessons policies
drop policy if exists "Admins can read lessons" on public.lessons;
drop policy if exists "Approved class students can read lessons" on public.lessons;
drop policy if exists "Admins can write lessons" on public.lessons;

create policy "Admins can read lessons"
on public.lessons for select
to authenticated
using (public.is_admin(auth.uid()));

create policy "Approved class students can read lessons"
on public.lessons for select
to authenticated
using (
  public.is_approved_student(auth.uid())
  and exists (
    select 1
    from public.class_memberships
    where student_id = auth.uid()
      and status = 'approved'
  )
);

create policy "Admins can write lessons"
on public.lessons for all
to authenticated
using (public.is_admin(auth.uid()))
with check (public.is_admin(auth.uid()));

-- student_lesson_progress policies
drop policy if exists "Students can read own approved-class progress" on public.student_lesson_progress;
drop policy if exists "Students can insert own approved-class progress" on public.student_lesson_progress;
drop policy if exists "Students can update own approved-class progress" on public.student_lesson_progress;
drop policy if exists "Admins can read all progress" on public.student_lesson_progress;

create policy "Students can read own approved-class progress"
on public.student_lesson_progress for select
to authenticated
using (
  student_id = auth.uid()
  and public.is_approved_student(auth.uid())
  and public.is_class_member(auth.uid(), class_id)
);

create policy "Students can insert own approved-class progress"
on public.student_lesson_progress for insert
to authenticated
with check (
  student_id = auth.uid()
  and public.is_approved_student(auth.uid())
  and public.is_class_member(auth.uid(), class_id)
);

create policy "Students can update own approved-class progress"
on public.student_lesson_progress for update
to authenticated
using (
  student_id = auth.uid()
  and public.is_approved_student(auth.uid())
  and public.is_class_member(auth.uid(), class_id)
)
with check (
  student_id = auth.uid()
  and public.is_approved_student(auth.uid())
  and public.is_class_member(auth.uid(), class_id)
);

create policy "Admins can read all progress"
on public.student_lesson_progress for select
to authenticated
using (public.is_admin(auth.uid()));

-- student_activity_logs policies
drop policy if exists "Students can insert own activity" on public.student_activity_logs;
drop policy if exists "Students can read own activity" on public.student_activity_logs;
drop policy if exists "Admins can read all activity" on public.student_activity_logs;

create policy "Students can insert own activity"
on public.student_activity_logs for insert
to authenticated
with check (student_id = auth.uid());

create policy "Students can read own activity"
on public.student_activity_logs for select
to authenticated
using (student_id = auth.uid());

create policy "Admins can read all activity"
on public.student_activity_logs for select
to authenticated
using (public.is_admin(auth.uid()));

-- 9. Triggers
-- update_updated_at_column
create or replace function public.update_updated_at_column()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists update_profiles_updated_at on public.profiles;
create trigger update_profiles_updated_at
before update on public.profiles
for each row execute function public.update_updated_at_column();

drop trigger if exists update_classes_updated_at on public.classes;
create trigger update_classes_updated_at
before update on public.classes
for each row execute function public.update_updated_at_column();

drop trigger if exists update_class_memberships_updated_at on public.class_memberships;
create trigger update_class_memberships_updated_at
before update on public.class_memberships
for each row execute function public.update_updated_at_column();

drop trigger if exists update_lessons_updated_at on public.lessons;
create trigger update_lessons_updated_at
before update on public.lessons
for each row execute function public.update_updated_at_column();

drop trigger if exists update_student_lesson_progress_updated_at on public.student_lesson_progress;
create trigger update_student_lesson_progress_updated_at
before update on public.student_lesson_progress
for each row execute function public.update_updated_at_column();

-- handle_new_user trigger
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (
    id,
    full_name,
    phone,
    email,
    role,
    status
  )
  values (
    new.id,
    coalesce(new.raw_user_meta_data->>'full_name', 'Học viên mới'),
    new.raw_user_meta_data->>'phone',
    new.email,
    'student',
    'pending'
  )
  on conflict (id) do update
  set
    email = excluded.email,
    phone = coalesce(excluded.phone, profiles.phone),
    full_name = coalesce(excluded.full_name, profiles.full_name);
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- 10. Performance Indexes
create index if not exists profiles_status_idx on public.profiles(status);
create index if not exists profiles_role_idx on public.profiles(role);
create index if not exists profiles_email_idx on public.profiles(email);
create index if not exists classes_status_idx on public.classes(status);
create index if not exists class_memberships_class_idx on public.class_memberships(class_id);
create index if not exists class_memberships_student_idx on public.class_memberships(student_id);
create index if not exists class_memberships_status_idx on public.class_memberships(status);
create index if not exists lessons_lesson_number_idx on public.lessons(lesson_number);
create index if not exists student_lesson_progress_student_idx on public.student_lesson_progress(student_id);
create index if not exists student_lesson_progress_class_idx on public.student_lesson_progress(class_id);
create index if not exists student_lesson_progress_lesson_idx on public.student_lesson_progress(lesson_id);
create index if not exists student_activity_logs_student_idx on public.student_activity_logs(student_id);
create index if not exists student_activity_logs_lesson_idx on public.student_activity_logs(lesson_id);

-- 11. Realtime setup
do $$
declare
  target_table text;
begin
  foreach target_table in array array[
    'profiles',
    'classes',
    'class_memberships',
    'lessons',
    'student_lesson_progress',
    'student_activity_logs'
  ]
  loop
    if not exists (
      select 1
      from pg_publication_tables
      where pubname = 'supabase_realtime'
        and schemaname = 'public'
        and tablename = target_table
    ) then
      execute format('alter publication supabase_realtime add table public.%I', target_table);
    end if;
  end loop;
end $$;

-- 12. Safe Admin promotion script
do $$
declare
  admin_uid uuid;
begin
  select id into admin_uid
  from auth.users
  where email = 'admin@gmail.com'
  limit 1;

  if admin_uid is not null then
    insert into public.profiles (id, full_name, email, role, status)
    values (admin_uid, 'Admin', 'admin@gmail.com', 'admin', 'approved')
    on conflict (id) do update
    set role = 'admin',
        status = 'approved',
        full_name = 'Admin',
        email = 'admin@gmail.com';
    raise notice 'Successfully promoted admin@gmail.com to admin.';
  else
    raise notice 'User admin@gmail.com does not exist in auth.users. Cannot promote to admin.';
  end if;
end $$;
